import { useCallback, useEffect, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import toast from "react-hot-toast";
import { cancelOrder, getOrders } from "../../api/orders";

const statuses = ["Pending", "Confirmed", "Processing", "Shipped", "Delivered", "Cancelled"];
const MyOrders = () => {
  const [params, setParams] = useSearchParams();
  const page = Math.max(1, Number(params.get("page")) || 1); const status = params.get("status") || "";
  const [data, setData] = useState(null); const [error, setError] = useState("");
  const load = useCallback(() => getOrders({ page, limit: 10, ...(status && { status }) }).then((value) => { setData(value); setError(""); }).catch((requestError) => setError(requestError.response?.data?.message || "Could not load orders.")), [page, status]);
  useEffect(() => { load(); }, [load]);
  const navigatePage = (nextPage) => { const next = new URLSearchParams(params); next.set("page", nextPage); setParams(next); };
  const changeStatus = (event) => { const next = new URLSearchParams(); if (event.target.value) next.set("status", event.target.value); setParams(next); };
  const cancel = async (order) => { if (!window.confirm(`Cancel ${order.orderNumber}? Stock will be restored.`)) return; try { await cancelOrder(order._id); toast.success("Order cancelled"); load(); } catch (requestError) { toast.error(requestError.response?.data?.message || "Cancellation failed"); } };
  return <section><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="heading text-4xl">My Orders</h1><p className="mt-2 text-neutral/60">Only orders placed through your signed-in account appear here.</p></div><label><span className="mb-1 block text-sm">Status</span><select value={status} onChange={changeStatus} className="select select-bordered"><option value="">All Orders</option>{statuses.map((value) => <option key={value}>{value}</option>)}</select></label></div>{error && <div className="alert alert-error mt-5">{error}</div>}{!data && !error && <div className="mt-10 text-center"><span className="loading loading-spinner loading-lg text-primary" /></div>}{data && <><div className="mt-7 space-y-4">{data.orders.map((order) => <article key={order._id} className="rounded-3xl bg-white p-5 shadow-sm"><div className="grid gap-3 md:grid-cols-[1.4fr_1fr_1fr_1fr_auto] md:items-center"><div><strong>{order.orderNumber}</strong><p className="text-sm text-neutral/50">{new Date(order.createdAt).toLocaleDateString()}</p></div><span>{order.items.reduce((sum, item) => sum + item.quantity, 0)} items</span><strong>৳ {order.total}</strong><div className="flex flex-wrap gap-2"><span className="badge badge-outline">{order.payment.status.replaceAll("_", " ")}</span><span className="badge badge-primary">{order.orderStatus}</span></div><div className="flex gap-2"><Link className="btn btn-primary btn-sm" to={`/dashboard/orders/${order._id}`}>View Details</Link>{order.orderStatus === "Pending" && <button type="button" onClick={() => cancel(order)} className="btn btn-error btn-outline btn-sm">Cancel</button>}</div></div></article>)}{!data.orders.length && <div className="rounded-3xl bg-white p-10 text-center"><h2 className="heading text-2xl">No orders yet</h2><p className="mt-2 text-neutral/60">No registered orders match this filter.</p><Link to="/shop" className="btn btn-primary mt-5 rounded-full">Start Shopping</Link></div>}</div>{data.totalPages > 1 && <div className="mt-7 flex items-center justify-center gap-3"><button disabled={page <= 1} onClick={() => navigatePage(page - 1)} className="btn btn-outline">Previous</button><span>Page {page} of {data.totalPages}</span><button disabled={page >= data.totalPages} onClick={() => navigatePage(page + 1)} className="btn btn-outline">Next</button></div>}</>}</section>;
};
export default MyOrders;
