import { useEffect, useMemo, useState } from "react";
import { useForm } from "react-hook-form";
import { useNavigate, useParams } from "react-router-dom";
import toast from "react-hot-toast";
import { getCategories } from "../../api/categories";
import { createProduct, getAdminProducts, updateProduct } from "../../api/products";
import { parseImageUrls } from "../../services/imageService";

const empty = { name: "", description: "", category: "", subcategory: "", brand: "", price: "", compareAtPrice: "", sku: "", stock: 0, lowStockThreshold: 5, images: "", specifications: "{}", variants: "[]", featured: false, bestseller: false, isNew: false, active: true };
const ProductForm = () => { const { id } = useParams(); const navigate = useNavigate(); const [categories, setCategories] = useState([]); const [loadError, setLoadError] = useState(""); const { register, handleSubmit, reset, watch, formState: { errors, isSubmitting } } = useForm({ defaultValues: empty }); const selectedCategory = watch("category"); const subcategories = useMemo(() => categories.find((c) => c.name === selectedCategory)?.subcategories || [], [categories, selectedCategory]);
  useEffect(() => { Promise.all([getCategories(), id ? getAdminProducts() : Promise.resolve(null)]).then(([categoryData, productData]) => { setCategories(categoryData.categories); if (id) { const p = productData.products.find((item) => item._id === id); if (!p) throw new Error("Product not found"); reset({ ...p, compareAtPrice: p.compareAtPrice ?? "", images: (p.images || []).join("\n"), specifications: JSON.stringify(p.specifications || {}, null, 2), variants: JSON.stringify(p.variants || [], null, 2) }); } }).catch((e) => setLoadError(e.response?.data?.message || e.message)); }, [id, reset]);
  const submit = async (values) => { try { const payload = { ...values, price: Number(values.price), compareAtPrice: values.compareAtPrice === "" ? null : Number(values.compareAtPrice), stock: Number(values.stock), lowStockThreshold: Number(values.lowStockThreshold), images: parseImageUrls(values.images), specifications: JSON.parse(values.specifications || "{}"), variants: JSON.parse(values.variants || "[]") }; if (id) await updateProduct(id, payload); else await createProduct(payload); toast.success(id ? "Product updated" : "Product created"); navigate("/admin/products"); } catch (e) { toast.error(e.response?.data?.errors?.join(", ") || e.response?.data?.message || e.message); } };
  if (loadError) return <div className="alert alert-error">{loadError}</div>;
  const field = "input input-bordered w-full rounded-xl"; return <section><p className="uppercase tracking-[4px] text-primary">Catalog</p><h1 className="heading mt-2 text-5xl">{id ? "Edit Product" : "Add Product"}</h1><form onSubmit={handleSubmit(submit)} className="mt-8 space-y-8 rounded-3xl bg-white p-8"><div className="grid gap-5 md:grid-cols-2"><label className="md:col-span-2">Name<input className={field} {...register("name", { required: "Name is required" })} />{errors.name && <span className="text-sm text-error">{errors.name.message}</span>}</label><label className="md:col-span-2">Description<textarea className="textarea textarea-bordered min-h-32 w-full rounded-xl" {...register("description", { required: true })} /></label><label>Category<select className="select select-bordered w-full rounded-xl" {...register("category", { required: true })}><option value="">Select category</option>{categories.map((c) => <option key={c._id} value={c.name}>{c.name}</option>)}</select></label><label>Subcategory<select className="select select-bordered w-full rounded-xl" {...register("subcategory")}><option value="">None</option>{subcategories.map((name) => <option key={name}>{name}</option>)}</select></label>{[["Brand", "brand"], ["Price", "price", "number"], ["Compare At Price", "compareAtPrice", "number"], ["SKU", "sku"], ["Stock", "stock", "number"], ["Low Stock Threshold", "lowStockThreshold", "number"]].map(([label, name, type]) => <label key={name}>{label}<input type={type || "text"} min={type ? 0 : undefined} step={name.includes("Price") || name === "price" || name === "compareAtPrice" ? "0.01" : "1"} className={field} {...register(name, { required: ["price", "sku", "stock"].includes(name) })} /></label>)}<label className="md:col-span-2">Image URLs (one per line)<textarea className="textarea textarea-bordered min-h-28 w-full rounded-xl" {...register("images")} /></label><label>Specifications (JSON object)<textarea className="textarea textarea-bordered min-h-40 w-full font-mono text-sm" {...register("specifications")} /></label><label>Optional variants (JSON array)<textarea className="textarea textarea-bordered min-h-40 w-full font-mono text-sm" {...register("variants")} /><span className="text-xs text-neutral/50">Each variant: sku, attributes, price, compareAtPrice, stock, active.</span></label></div><div className="flex flex-wrap gap-6">{[["featured", "Featured"], ["bestseller", "Bestseller"], ["isNew", "New"], ["active", "Active"]].map(([name, label]) => <label key={name} className="flex items-center gap-2"><input type="checkbox" className="checkbox checkbox-primary" {...register(name)} />{label}</label>)}</div><button disabled={isSubmitting} className="btn btn-primary rounded-full px-10">{isSubmitting ? "Saving..." : "Save Product"}</button></form></section>; };
export default ProductForm;
